main.tf
variables.tf
versions.tf

related to aws provider version 2.47.0

terraform-provider-aws update

---

main.tf

I was receiving the following error from the commit adding case_sensitive:
```
Error: Unsupported argument
on terraform-aws-cognito-user-pool/main.tf line 12, in resource "aws_cognito_user_pool" "pool":
12:   username_configuration = {
An argument named "username_configuration" is not expected here. Did you mean
to define a block of type "username_configuration"?
```
This pr fixes the error :)

applies case_sensitive via username_configuration

---

main.tf

I'd consider this a temporary solution, until we get module lifecycle support in terraform and [#3891](https://github.com/hashicorp/terraform-provider-aws/issues/3891).
The latter is on the current [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/606ed39bfd0e13d2189000db084c5e0b1c7105c2/ROADMAP.md)
Basically it enables schema changes on the existing pool, without destroying it.
EDIT: To clarify, only aws console or cli support schema modifications currently..

Ignore schema changes and prevent pool destruction

---

examples/complete/README.md
examples/complete/main.tf

The property is called `access_token_validity` and not `access_validity`
(At least from my understanding of https://github.com/lgallard/terraform-aws-cognito-user-pool/blob/master/CHANGELOG.md#0100-april-10-2021 and of 
https://github.com/lgallard/terraform-aws-cognito-user-pool/blob/79870ee74546392b4bebce5133139313556f2e15/client.tf#L13
)

Fix incorrect example with access_token_validity

---

outputs.tf

Newer terraform version throws an error on applying the module since the client_secrets output variable must be marked as sensitive.

set client_secrets output to be sensitive

---

examples/complete/main.tf
identity-provider.tf
variables.tf

This adds support for Cognito Identity Providers to the user pool. I have extended the complete example. I was able to deploy the example with Terraform successfully, with this addition.

Add support for Cognito Identity Providers

---

variables.tf

The default values result in a access and id token validity period of 60
hours. Values are only accepted in the range 5 minutes to 1 day. I
suspect the original intention was to make this an hour.
Fixes #68

Fixes #68 Use accepted token validity periods

---

client.tf

Fixes #71 
After trying this change locally, it never fails deployment again due to InvalidParameterException: The provider XXXXXX does not exist for User Pool YYYYYY

Add identity provider as a dependency for aws_cognito_user_pool_client

---

variables.tf

The default value for `client_prevent_user_existence_errors` is invalid. So not setting it (like in `examples/simple_extended`) ends in an error like this:
```
$ terraform apply
╷
│ Error: expected prevent_user_existence_errors to be one of [LEGACY ENABLED], got 
│ 
│   with module.aws_cognito_user_pool_simple_extended_example.aws_cognito_user_pool_client.client[0],
│   on .terraform/modules/aws_cognito_user_pool_simple_extended_example/client.tf line 17, in resource "aws_cognito_user_pool_client" "client":
│   17:   prevent_user_existence_errors        = lookup(element(local.clients, count.index), "prevent_user_existence_errors", null)
│ 
╵
```

fix:  `client_prevent_user_existence_errors` default value is invalid

---

main.tf

- `string_attribute_constraints` is `number_attribute_constraints` should be null or map so use `keys()` to dynamically decide to add values
- `min_value` and `max_value` are optional value so default to `null`

fix the attributes constraints for number and string schemas

---

variables.tf

Set the variaable `identity_providers` to `sensitive = true`.
The information in this variable, especially `client_secret`, could be sensitive.

Set `identity_providers` variable to sensitive

---

variables.tf

Hey there 👋,
I noticed a duplicate `require_lowercase` key in the `password_policy` input variable. It doesn't hurt, but at least it's one line less to maintain 😊 
:octocat:

Remove duplicate `require_lowercase` key for password policies

---

main.tf
variables.tf

Change to fix https://github.com/lgallard/terraform-aws-cognito-user-pool/issues/112. Issue was still looping when `user_attribute_update_settings` was `null` due to list still having an empty map inside it.

Fix user attribute update settings lookup

---

README.md
outputs.tf

Add `name` to output because some resources and data sources, for example `data.aws_cognito_user_pools` expect to have a name as input, not `id`, but current version of the module doesn't provide this attribute

Add name to output

---

main.tf

fix: make sure attribute_constraints are created for string and number schemas

---

CHANGELOG.md
main.tf

FIXES:
* Add back previously removed lifecyle ignore block (thanks @chris-symbiote)

Add back previously removed lifecyle ignore block

---

main.tf

The error I was getting:
```
│ Error: Reference to undeclared resource
│
│   on .terraform/modules/cognito_user_pool/main.tf line 76, in resource "aws_cognito_user_pool" "pool":
│   76:           lambda_arn     = lookup(for_each.value, "lambda_arn", null)
│
│ A managed resource "for_each" "value" has not been declared in
│ module.cognito_user_pool.
╵
```
So I decided to test a couple things, `each.value`, `each.key` etc. but none of them worked. 
```
│ A reference to "each.value" has been used in a context in which it
│ unavailable, such as when the configuration no longer contains the value in
│ its "for_each" expression. Remove this reference to each.value in your
│ configuration to work around this error.
```
So I just decided to make it consistent with other lambda blocks by …

fix: lambda customization config not working

---

outputs.tf

This change enables to expose the domain name associated to the generated CloudFront distribution.
For IaC scenarions, it is mandatory in order to generate a custom CNAME record pointing to that distribution.
@lgallard This is the same change you introduced in 63e5ec8 but for the CloudFront domain name.

Add domain cloudfront_distribution name attribute as output

---

README.md
client.tf
domain.tf
identity-provider.tf
main.tf
outputs.tf
resource-server.tf
ui-customization.tf
user-group.tf
variables.tf

Fixes the perpetual diff issue described in #194 where Cognito User Pool schemas are continuously planned for destruction and recreation on every `terraform plan`, even when no configuration changes are made.
AWS Cognito User Pool schemas cannot be modified or removed after creation. The AWS API returns schema information in a different format than what was originally sent (different ordering, additional empty constraint blocks), causing Terraform to detect changes where none exist and attempt to recreate schemas, which fails with AWS API errors.
**Important:** Terraform does not support conditional expressions in `lifecycle.ignore_changes` blocks. According to the [official documentation](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle):
> "The lifecycle …

fix: resolve schema perpetual diff issue with ignore_schema_changes variable

---

README.md
main.tf
variables.tf

support setting user pool tier.
Requested feature at https://github.com/lgallard/terraform-aws-cognito-user-pool/issues/167
Default value gets set to Essentials because as per AWS documentation https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-sign-in-feature-plans.html "The default plan selection for new user pools is Essentials."
user_pool_tier option was introduced to aws provider at version 5.83 https://github.com/hashicorp/terraform-provider-aws/blob/v5.83.0/CHANGELOG.md so the existing min 5.95 version constraint at https://github.com/lgallard/terraform-aws-cognito-user-pool/blob/master/versions.tf#L6 satisfies the introduced attribute

feat: support user pool tier option

---

README.md
outputs.tf

- Fixes unsupported attribute error when accessing `.arn` on `aws_cognito_user_group` resource
- The `aws_cognito_user_group` resource does not expose an `arn` attribute in the Terraform AWS provider
- Constructs user group ARNs manually using the user pool ARN and group name
- Updated `user_group_arns` output to construct ARNs using `"${local.user_pool.arn}/group/${group.name}"`
- Updated `user_groups_map` output to use the same constructed ARN pattern
- ARN format follows AWS standard: `arn:aws:cognito-idp:region:account-id:userpool/user-pool-id/group/group-name`
Fixes #205

fix: resolve unsupported attribute error for user_groups_map ARN

---

examples/with_branding/README.md
examples/with_branding/assets/README.md
examples/with_branding/main.tf
variables.tf

Fixes color_mode validation errors in the `examples/with_branding` example that occur when using the awscc provider.
The with_branding example used `"BROWSER_ADAPTIVE"` as color_mode values for background and favicon assets, but the awscc provider only accepts `["LIGHT", "DARK", "DYNAMIC"]`. This caused terraform plan to fail with validation errors.
- **Changed** `"BROWSER_ADAPTIVE"` to `"DYNAMIC"` in `examples/with_branding/main.tf` (lines 60, 66)
- **Updated** validation rule in `variables.tf` to accept `"DYNAMIC"` instead of `"BROWSER_ADAPTIVE"`
✅ `terraform validate` passes  
✅ `terraform plan` executes without validation errors  
✅ awscc_cognito_managed_login_branding resource creates successfully  
- `examples/with_branding/main.tf` - Updated asset color_mode values
- `variables.tf` …

Fix color_mode validation errors in with_branding example

---

examples/with_branding/assets/favicon.svg
examples/with_branding/assets/logo-dark.svg
examples/with_branding/assets/logo-light.svg
examples/with_branding/main.tf
examples/with_branding/terraform.tfvars

This PR fixes several critical issues with the `examples/with_branding` example to ensure AWS Cognito managed login branding works correctly out-of-the-box.
- Missing `enable_branding = true` variable causing conditional logic to fail
- Incompatible settings JSON structure rejected by AWS API
- Generic domain name causing conflicts during testing
- SVG `dominant-baseline` attribute not allowed by AWS validation
- Logo size too small (200x60px) for good visibility
- FAVICON_ICO using SVG format instead of required ICO format
- Missing light/dark variants for different logo categories
- ✅ Add `enable_branding = true` to `terraform.tfvars`
- ✅ Use `use_cognito_provided_values = true` for AWS-compatible settings
- ✅ Configure multiple asset categories: `PAGE_HEADER_LOGO`, `FORM_LOGO`, …

fix(examples): improve with_branding example configuration and assets

---

CLAUDE.md

Documents the design decision to maintain dual `aws_cognito_user_pool` resources despite significant code duplication (~252 lines).
Following the analysis in PR #271, this documents why we **intentionally maintain** code duplication for schema change visibility.
- **CLAUDE.md**: Added "Design Decisions" section explaining dual-resource rationale
- Documents trade-off between code duplication vs workflow visibility  
- References PR #271 analysis for future maintainers
- Prevents future attempts to "fix" this intentional design
Schema change visibility in terraform plans is essential for:
1. **Change Review Workflows** - Teams need to see schema additions in plans
2. **Compliance Requirements** - Organizations require approval for new user attributes
3. **Application Coordination** - Apps …

docs: document schema visibility design decision

---

.github/workflows/claude-code-review.yml

This PR resolves the root cause of the codebot workflow failures identified in workflow run #18049456481.
The repository dispatch was failing with a 403 error:
```
gh: Resource not accessible by integration (HTTP 403)
{\"message\":\"Resource not accessible by integration\",\"documentation_url\":\"https://docs.github.com/rest/repos/repos#create-a-repository-dispatch-event\",\"status\":\"403\"}
```
`GITHUB_TOKEN` lacks permission to trigger `repository_dispatch` events due to GitHub's security restrictions. This is a known limitation where the default GitHub Actions token cannot trigger repository dispatch events.
Replace `GITHUB_TOKEN` with `CLAUDE_CODE_OAUTH_TOKEN` in the comment-dispatch job (line 162).
**The fix:**
```yaml
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
env: …
```

fix: use CLAUDE_CODE_OAUTH_TOKEN for repository dispatch authentication

---

.github/workflows/claude-code-review.yml

The codebot was generating analysis successfully but NOT posting comments. Investigation revealed the issue:
```
##[warning]Unexpected input(s) 'allowed_tools', valid inputs are ['trigger_phrase', 'assignee_trigger', 'label_trigger', ...]
```
The `allowed_tools` parameter **does not exist** in Claude Code Action v1.0.0. This invalid parameter was causing the entire configuration to fail silently, preventing comment posting even though analysis was being generated.
✅ **Analysis Generated**: Full bug hunt results visible in workflow logs  
❌ **Comments Not Posted**: Invalid configuration prevented posting  
⚠️  **Warning Generated**: "Unexpected input(s) 'allowed_tools'"
Remove the unsupported `allowed_tools` parameter. Claude Code Action v1.0.0 has its own internal mechanism for comment …

fix: Remove unsupported allowed_tools parameter from Claude Code Action v1.0.0

---

.github/workflows/claude-code-review.yml

The codebot workflow was failing with 'command not found' errors when processing comments containing backticks (like `allowed_tools`). The issue was in the comment parsing step where echo was executing words as commands.
- Replace echo with printf for safer comment text handling
- Prevents bash from trying to execute words like 'allowed_tools' as commands
- Fixes the 'command not found' error when processing comments with code syntax
- Maintains same text filtering and safety measures
This should resolve the bash parsing error seen in recent workflow runs where allowed_tools was being treated as a command.
Fixes the codebot comment posting functionality.

fix: Fix comment parsing to prevent bash command execution

---

.github/workflows/claude-code-review.yml

This PR addresses a command injection vulnerability in the codebot workflow.
The comment body was being directly interpolated into bash scripts using `${{ github.event.comment.body }}`, which meant any words in user comments could be executed as bash commands, causing errors like:
- `backticks: command not found`
- `allowed_tools: command not found`
- Move comment body to environment variable (`env: COMMENT_BODY`)
- Access via `$COMMENT_BODY` instead of direct interpolation
- Prevents GitHub Actions from injecting user input directly into bash script
- Maintains same text filtering and safety measures
This prevents potential command injection attacks where malicious comments could execute arbitrary bash commands in the workflow environment.
Fixes the remaining bash parsing errors in the …

fix: Use environment variable for comment body to prevent command injection

---

.github/workflows/claude-code-review.yml

Fixes the critical issue where codebot workflow only shows eyes emoji reactions but never posts analysis comments.
After analyzing the working `claude.yml` vs broken `claude-code-review.yml` and reviewing the official Claude Code Action v1.0 documentation, the issue was:
- **Missing comment tools**: Claude Code Action v1.0 requires explicit tool permissions via `claude_args` for GitHub commenting
- **Working claude.yml**: Uses deprecated `allowed_tools` parameter (still works for backward compatibility)
- **Broken codebot**: Modern syntax but missing essential `Bash(gh pr comment:*)` tool permissions
- ✅ **Added `claude_args`** with required GitHub commenting tools:
- `Bash(gh pr comment:*)` - For posting PR comments  
- `Bash(gh api:*)` - For GitHub API access
- Preserved existing MCP …

fix: add required GitHub commenting tools to codebot workflow

---

.github/workflows/claude-code-review.yml

This PR contains **critical security and functionality fixes** for the codebot workflow.
The `parse-command` step had a **command injection vulnerability** where user comment content was being executed as shell commands.
**Attack Vector:**
```bash
@codebot hunt - Added `claude_args` with `Bash(gh pr comment:*)`
COMMENT_BODY="@codebot hunt - Added `claude_args` with `Bash(gh pr comment:*)`"
```
**Error Evidence:**
```
line 6: claude_args: command not found
syntax error near unexpected token `gh'
command substitution: line 6: `Bash(gh pr comment:*)'
```
**Security Fix:**
- ✅ **Environment variable isolation**: Move comment body to env var instead of direct assignment
- ✅ **Safe processing**: Use `printf` instead of `echo` for safer content handling
- ✅ **Input sanitization**: Maintain …

CRITICAL: Fix codebot command injection vulnerability + add required comment tools

---

.github/workflows/claude-code-review.yml

The codebot workflow (claude-code-review.yml) was completing successfully but not posting analysis comments. The eyes emoji reactions worked, but Claude wasn't commenting back with analysis.
Based on Claude Code Action documentation research:
1. **Wrong Parameter Format**: Using `claude_args: | --allowedTools` instead of `allowed_tools: "string"`
2. **Missing Trigger Bridge**: Workflow detected "codebot" mentions but Claude expected its trigger phrase
3. **GitHub Context Issues**: Using `github.event.pull_request.number` in comment events where it may not exist
4. **No Explicit Comment Instruction**: Custom prompt didn't tell Claude to post a comment
- Replaced `claude_args: | --allowedTools` with `allowed_tools: "string"` (v1.0 format)
- Matches working claude.yml pattern
- Added …

fix: correct Claude Code Action parameters for codebot commenting

---

.github/workflows/claude-code-review.yml

The codebot workflow was still not posting comments despite the previous fix. Investigation of the workflow logs revealed a critical issue:
```
##[warning]Unexpected input(s) 'allowed_tools', valid inputs are ['trigger_phrase', 'assignee_trigger', 'label_trigger', ...]
```
The `allowed_tools` parameter is **not recognized** by Claude Code Action v1.0.0, which means Claude didn't have access to the GitHub commenting tools.
- Claude Code Action v1.0.0 doesn't support `allowed_tools` as a direct parameter
- The valid inputs list shows `claude_args` is the correct way to pass tool permissions
- Without proper tool permissions, Claude can't post comments even with explicit instructions
- Changed from `allowed_tools: "..."` to `claude_args: "--allowedTools ..."`
- This matches the format …

fix: use claude_args instead of unrecognized allowed_tools parameter

---

.github/workflows/claude-code-review.yml
.github/workflows/claude.yml

Fixes permission denied errors when Claude tries to use MCP servers in GitHub Actions by correcting the tool names in `allowed_tools` configurations.
Claude was encountering "Permission denied" errors when attempting to use Terraform MCP server tools in GitHub Actions, despite successful local testing. The issue was a mismatch between the configured tool names and the actual function signatures.
The `allowed_tools` configuration used outdated or incorrect function names:
- `mcp__terraform-server__getProviderDocs` (incorrect)
- `mcp__terraform-server__resolveProviderDocID` (incorrect)
- `mcp__terraform-server__searchModules` (incorrect)
- `mcp__terraform-server__moduleDetails` (incorrect)
Updated both workflow files with the correct MCP tool function names:
- …

fix: correct MCP server tool names in GitHub Actions workflows
