lgallard/terraform-aws-cognito-user-pool

- main.tf
Temporary solution for the fixing bug
https://github.com/terraform-providers/terraform-provider-aws/issues/11858
> Fix aws provider bug

- client.tf
- resource-server.tf
- user-group.tf
> Tupple -> Tuple

- main.tf
- variables.tf
> adding case sensitive var

- README.md
- examples/complete.tf
- main.tf
- variables.tf
Resolution to https://github.com/lgallard/terraform-aws-cognito-user-pool/issues/13
Add support for software TOTP mfa tokens.
> Add support for software_token_mfa_configuration

- CHANGELOG.md
- README.md
- examples/complete.tf
- main.tf
- variables.tf
- versions.tf
*  Add support for `software_token_mfa_configuration`
* Fix Terraform formating
* Update README
> Release 0.4.0

- CHANGELOG.md
- README.md
- examples/complete.tf
- main.tf
Deprecate `unused_account_validity_days` field
> Deprecate unused_account_validity_days field

- README.md
- examples/complete/main.tf
- examples/simple/main.tf
- examples/simple_extended/main.tf
* Change source in examples to use Terraform format
> Change source in examples

- README.md
- client.tf
- domain.tf
- main.tf
- outputs.tf
- resource-server.tf
- user-group.tf
- variables.tf
Update:
* support `create_user_pool` for conditional creation of cognito user pool
* remove `prevent_destroy = true` incase user want to delete their cognito user pool via `create_user_pool = false`
* documentation/example added for `create_user_pool` variable
> Support conditional creation

- CHANGELOG.md
- README.md
- variables.tf
> Set default value for enable variable to true

- domain.tf
- examples/complete/variables.tf
- examples/simple/variables.tf
- examples/simple_extended/variables.tf
- main.tf
- variables.tf
The `terraform fmt -recursive -check -diff` command fails with version >=0.14. This should solve it.
You may review the variable types to be more precise than `any`.
> feat(terraform): make code formatting work with terraform >= 0.14

- README.md
- examples/complete/main.tf
- main.tf
- variables.tf
Adds feature to prevent the userpool from being deleted --> https://github.com/lgallard/terraform-aws-cognito-user-pool/issues/53
> 53: Prevent deletion of the userpool via parameter

- main.tf
- variables.tf
Add support for custom_email_sender, custom_sms_sender and kms_key_in in lambda_config
> Extend parameter support in lambda_config

- .pre-commit-config.yaml
- CHANGELOG.md
- README.md
- examples/complete/main.tf
- main.tf
- variables.tf
> Fix lambda config keeps changing

- README.md
- client.tf
- variables.tf
Adding an option to revoke client tokens.
> Add missing option to allow client token revocation

- CHANGELOG.md
FIXES:
* Fix ´username_configuration´ typo in README (thanks @ajoga and @KelvinVenancio)
> Fix username_configuration typo in README

- README.md
- examples/complete/README.md
- examples/complete/main.tf
- main.tf
- variables.tf
Fixes #53 
Uses newly added argument https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#deletion_protection
> Add support for user pool deletion_protection

- CHANGELOG.md
- README.md
- versions.tf
> Bump AWS provider minimum version to 4.38

- README.md
- main.tf
- variables.tf
This PR adds handling for the user_attribute_update_settings option
It is a recent addition to the AWS provider, see https://github.com/hashicorp/terraform-provider-aws/issues/26726
> Add user_attribute_update_settings to user pool

- CHANGELOG.md
- README.md
ENHANCEMENTS:
* Add support for `auth_session_validity` parameter to user pool client (thanks @xposix)
> Release support for auth_session_validity parameter 

- CHANGELOG.md
ENHANCEMENTS:
* Add Cognito User Pool name as output (thanks @SlavaNL)
> Add Cognito User Pool name as output

- CHANGELOG.md
FIXES:
* Fix dynamic `pre_token_generation_config` args (thanks @lgallard)
> Release for fix dynamic pre_token_generation_config args

- CHANGELOG.md
- main.tf
Fix case when no `pre_token_generation_config` is present
> Fix case when no `pre_token_generation_config` is present

- CHANGELOG.md
FIXES:
* Fix lambda customization config not working (thanks @Dogacel)
> Release 0.27.3

- CHANGELOG.md
ENHANCEMENTS:
* Add missing arguments for `verification_message_template` block (thanks @catrielg)
> Add missing - arguments for  block

- README.md
- domain.tf
- variables.tf
- versions.tf
- closes https://github.com/lgallard/terraform-aws-cognito-user-pool/issues/165
> [!WARNING]
> I've not tested these changes. I am not a terraform expert, please validate that these changes are correct and work as expected :)
> feature: Add variable to change hosting ui version

- CHANGELOG.md
This pull request updates the `CHANGELOG.md` file to document the release of version 0.35.0. It includes an enhancement that adds a variable to change the hosting UI version, with credit given to the contributor.
> Update CHANGELOG comments

- CHANGELOG.md
- README.md
ENHANCEMENTS:
* Add support for `email_mfa_configuration` parameter (thanks @bsipiak)
* Add example for email MFA configuration (thanks @lgallard)
This release includes all documentation and changelog updates for the new features and example.
> chore(release): prepare v0.36.0 with email MFA enhancements and example

- README.md
- examples/complete/README.md
- examples/complete/main.tf
- examples/email_mfa/README.md
- examples/email_mfa/main.tf
- examples/simple/README.md
- examples/simple/main.tf
- examples/simple_extended/README.md
- examples/simple_extended/main.tf
This PR fixes several formatting and documentation issues in the README that were identified after the schema fix implementation was merged. **All examples now include `ignore_schema_changes = true` with clear guidance for new deployments, documentation has been validated using terraform-docs, and ALL example files have been updated.**
- ✅ **Added missing HCL language specification** (`hcl`) to all code examples for proper syntax highlighting
- ✅ **Fixed missing closing backticks** in code blocks
- ✅ **Added `ignore_schema_changes = true` to ALL examples** with clear comments explaining importance
- ✅ **Enhanced best practice guidance** for new deployments
- ✅ **Validated with terraform-docs** to ensure consistency and accuracy
- ✅ **Complete auto-generated documentation** with all …
> docs: fix README formatting and complete documentation

- renovate.json
- Add renovate.json configuration for automated dependency updates
- Provides comprehensive Terraform ecosystem management
- Replaces manual dependency tracking with automated updates
- **Terraform providers**: Automatic updates with manual approval for major versions
- **Terraform modules**: Tracked and updated automatically  
- **Core terraform**: Version updates managed
- **Dependency dashboard**: Enabled for better visibility
- **Automerge**: Disabled for safety (manual review required)
- Automated tracking of Terraform provider and module updates
- Prevents security vulnerabilities from outdated dependencies
- Consistent with terraform-aws-secrets-manager dependency management
- Manual approval gate for major version changes ensures stability
> feat: add renovate dependency management

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- .terraform-docs.yml
- .tflint.hcl
- .trivy.yaml
- README.md
- client.tf
- examples/complete/README.md
- examples/complete/main.tf
- main.tf
- managed-login-branding.tf
- test/fixtures/validation-test/main.tf
- ui-customization.tf
- variables.tf
Add comprehensive pre-commit GitHub Actions workflow for automated code quality validation and formatting.
- Add pre-commit.yml workflow with Terraform formatting, validation, and linting
- Include terraform-docs for automatic documentation generation
- Add TFLint for advanced Terraform analysis and best practices
- Implement intelligent caching for improved performance
- Support incremental checking on pull requests
**Automated Code Quality:**
- 🔧 Terraform formatting (`terraform fmt`)
- ✅ Terraform validation (`terraform validate`)  
- 📚 Documentation generation (`terraform-docs`)
- 🔍 TFLint analysis for best practices
- 🧹 File formatting (trailing whitespace, end-of-file fixes)
- 📋 YAML validation
**Performance Optimizations:**
- Smart caching of terraform-docs and tflint binaries
- …
> feat: add pre-commit workflow for automated code quality

- .claude/agents/cognito-migration.md
- .claude/agents/module-documentation.md
- .claude/agents/terraform-cognito.md
- .claude/agents/terraform-security.md
- .claude/agents/terraform-testing.md
- Add Claude Code specialized agent configurations for enhanced development workflow
- Include agents for module documentation, security analysis, testing, migration support, and Cognito-specific development
- **module-documentation**: Documentation and example specialist for Terraform AWS Cognito User Pool module
- **terraform-security**: Security analysis and hardening specialist for Terraform AWS Cognito configurations  
- **terraform-testing**: Terratest and validation specialist for Terraform module testing
- **cognito-migration**: AWS Cognito upgrade and migration specialist for Terraform modules
- **terraform-cognito**: AWS Cognito User Pool specialist for Terraform infrastructure development
> Add Claude Code agent configurations

- .github/ISSUE_TEMPLATE/cognito-bug-fix.md
- .github/ISSUE_TEMPLATE/cognito-deprecation.md
- .github/ISSUE_TEMPLATE/new-cognito-feature.md
- .github/feature-tracker/cognito-features.json
- .github/scripts/discovery-prompt.md
- .github/workflows/claude-code-review.yml
- .github/workflows/claude.yml
- .github/workflows/feature-discovery.yml
- .github/workflows/pre-commit.yml
- MIGRATION.md
- README.md
- examples/simple_extended/README.md
- locals-device.tf
- test/fixtures/complete-config/main.tf
- test/fixtures/complete-config/outputs.tf
- test/fixtures/complete-config/variables.tf
- variables.tf
This PR implements an automated feature discovery system that runs weekly to identify new AWS Cognito User Pool features, deprecations, and bug fixes from the AWS provider. The system uses Claude Code with MCP (Model Context Protocol) servers to analyze provider documentation and automatically create GitHub issues for new functionality.
- **Schedule**: Every Sunday at 00:00 UTC
- **MCP Integration**: Terraform and Context7 MCP servers for real-time documentation access
- **Intelligent Analysis**: Compares provider capabilities with current module implementation
- **Manual Triggers**: Support for on-demand scans with dry-run mode
- **New Features** (🚀): Cognito resources/arguments not yet implemented
- **Deprecations** (⚠️): Features being phased out requiring action  
- **Bug Fixes** (🐛): …
> feat: Add automated Cognito User Pool feature discovery system

- .github/workflows/claude-code-review.yml
This PR restores the sophisticated codebot mode functionality while maintaining the reliable simplified architecture and adding support for both  and  trigger formats.
Both trigger formats now work identically:
- ✅  → security-focused review
- ✅  → security-focused review  
- ✅  → defaults to hunt mode
- ✅  → defaults to hunt mode
**5 distinct modes** with specialized prompts and subagent routing:
1. **🕵️ Hunt Mode** ( /  /  / )
- Quick bug detection and critical issue identification
- Focus: bugs, security vulnerabilities, performance issues
- Subagents: @terraform-cognito, @terraform-security, @terraform-testing
2. **📊 Analyze Mode** ( / )
- Deep technical analysis and architecture review
- Focus: architecture, patterns, complexity, maintainability
- Subagents: @terraform-cognito, …
> feat: Enhanced codebot with modes and flexible triggers (@codebot + codebot)
